#!/usr/bin/env bash
set -e
exec 2>&1
WDIR=/home/rubydev/bp1step/
LOG=$WDIR/log/bp1step.log
exec 1>>$LOG
cd $WDIR
echo
echo `date +'%Y.%m.%d %H:%M'`
# load rvm ruby
RPATH=`rvm env --path`
source $RPATH
# update users from active directory
rake bp1step:sync_active_directory_users
