require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BproceWorkplacesController do

  before(:each) do
    bproce = FactoryGirl.create(:bproce)
    workplace = FactoryGirl.create(:workplace)
    bproce_workplace = FactoryGirl.create(:bproce_workplace)
    bproce_workplace.bproce_id = bproce.id
    bproce_workplace.workplace_id = workplace.id
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BproceWorkplacesController. Be sure to keep this updated too.
  def valid_attributes
    {
      bproce_id: bproce.id,
      workplace_id: workplace.id
    }
  end
  def valid_session
    {}
  end

  describe "GET show" do
    it "assigns the requested bproce_workplace as @bproce_workplace" do
      bproce_workplace = BproceWorkplace.create! valid_attributes
      get :show, {:id => bproce_workplace.to_param}, valid_session
      assigns(:bproce_workplace).should eq(bproce_workplace)
    end
  end

  describe "GET new" do
    it "assigns a new bproce_workplace as @bproce_workplace" do
      get :new, {}, valid_session
      assigns(:bproce_workplace).should be_a_new(BproceWorkplace)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BproceWorkplace" do
        expect {
          post :create, {:bproce_workplace => valid_attributes}, valid_session
        }.to change(BproceWorkplace, :count).by(1)
      end

      it "assigns a newly created bproce_workplace as @bproce_workplace" do
        post :create, {:bproce_workplace => valid_attributes}, valid_session
        assigns(:bproce_workplace).should be_a(BproceWorkplace)
        assigns(:bproce_workplace).should be_persisted
      end

      it "redirects to the created bproce_workplace" do
        post :create, {:bproce_workplace => valid_attributes}, valid_session
        response.should redirect_to(BproceWorkplace.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bproce_workplace as @bproce_workplace" do
        # Trigger the behavior that occurs when invalid params are submitted
        BproceWorkplace.any_instance.stub(:save).and_return(false)
        post :create, {:bproce_workplace => {  }}, valid_session
        assigns(:bproce_workplace).should be_a_new(BproceWorkplace)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BproceWorkplace.any_instance.stub(:save).and_return(false)
        post :create, {:bproce_workplace => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bproce_workplace" do
        bproce_workplace = BproceWorkplace.create! valid_attributes
        # Assuming there are no other bproce_workplaces in the database, this
        # specifies that the BproceWorkplace created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BproceWorkplace.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => bproce_workplace.to_param, :bproce_workplace => { "these" => "params" }}, valid_session
      end

      it "assigns the requested bproce_workplace as @bproce_workplace" do
        bproce_workplace = BproceWorkplace.create! valid_attributes
        put :update, {:id => bproce_workplace.to_param, :bproce_workplace => valid_attributes}, valid_session
        assigns(:bproce_workplace).should eq(bproce_workplace)
      end

      it "redirects to the bproce_workplace" do
        bproce_workplace = BproceWorkplace.create! valid_attributes
        put :update, {:id => bproce_workplace.to_param, :bproce_workplace => valid_attributes}, valid_session
        response.should redirect_to(bproce_workplace)
      end
    end

    describe "with invalid params" do
      it "assigns the bproce_workplace as @bproce_workplace" do
        bproce_workplace = BproceWorkplace.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BproceWorkplace.any_instance.stub(:save).and_return(false)
        put :update, {:id => bproce_workplace.to_param, :bproce_workplace => {  }}, valid_session
        assigns(:bproce_workplace).should eq(bproce_workplace)
      end

      it "re-renders the 'edit' template" do
        bproce_workplace = BproceWorkplace.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BproceWorkplace.any_instance.stub(:save).and_return(false)
        put :update, {:id => bproce_workplace.to_param, :bproce_workplace => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bproce_workplace" do
      bproce_workplace = BproceWorkplace.create! valid_attributes
      expect {
        delete :destroy, {:id => bproce_workplace.to_param}, valid_session
      }.to change(BproceWorkplace, :count).by(-1)
    end

    it "redirects to the bproce_workplaces list" do
      bproce_workplace = BproceWorkplace.create! valid_attributes
      delete :destroy, {:id => bproce_workplace.to_param}, valid_session
      response.should redirect_to(bproce_workplaces_url)
    end
  end

end
