require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StaffsController do

  # This should return the minimal set of attributes required to create a valid
  # Staff. As you add validations to Staff, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all staffs as @staffs" do
      staff = Staff.create! valid_attributes
      get :index
      assigns(:staffs).should eq([staff])
    end
  end

  describe "GET show" do
    it "assigns the requested staff as @staff" do
      staff = Staff.create! valid_attributes
      get :show, :id => staff.id
      assigns(:staff).should eq(staff)
    end
  end

  describe "GET new" do
    it "assigns a new staff as @staff" do
      get :new
      assigns(:staff).should be_a_new(Staff)
    end
  end

  describe "GET edit" do
    it "assigns the requested staff as @staff" do
      staff = Staff.create! valid_attributes
      get :edit, :id => staff.id
      assigns(:staff).should eq(staff)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Staff" do
        expect {
          post :create, :staff => valid_attributes
        }.to change(Staff, :count).by(1)
      end

      it "assigns a newly created staff as @staff" do
        post :create, :staff => valid_attributes
        assigns(:staff).should be_a(Staff)
        assigns(:staff).should be_persisted
      end

      it "redirects to the created staff" do
        post :create, :staff => valid_attributes
        response.should redirect_to(Staff.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved staff as @staff" do
        # Trigger the behavior that occurs when invalid params are submitted
        Staff.any_instance.stub(:save).and_return(false)
        post :create, :staff => {}
        assigns(:staff).should be_a_new(Staff)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Staff.any_instance.stub(:save).and_return(false)
        post :create, :staff => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested staff" do
        staff = Staff.create! valid_attributes
        # Assuming there are no other staffs in the database, this
        # specifies that the Staff created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Staff.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => staff.id, :staff => {'these' => 'params'}
      end

      it "assigns the requested staff as @staff" do
        staff = Staff.create! valid_attributes
        put :update, :id => staff.id, :staff => valid_attributes
        assigns(:staff).should eq(staff)
      end

      it "redirects to the staff" do
        staff = Staff.create! valid_attributes
        put :update, :id => staff.id, :staff => valid_attributes
        response.should redirect_to(staff)
      end
    end

    describe "with invalid params" do
      it "assigns the staff as @staff" do
        staff = Staff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Staff.any_instance.stub(:save).and_return(false)
        put :update, :id => staff.id, :staff => {}
        assigns(:staff).should eq(staff)
      end

      it "re-renders the 'edit' template" do
        staff = Staff.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Staff.any_instance.stub(:save).and_return(false)
        put :update, :id => staff.id, :staff => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested staff" do
      staff = Staff.create! valid_attributes
      expect {
        delete :destroy, :id => staff.id
      }.to change(Staff, :count).by(-1)
    end

    it "redirects to the staffs list" do
      staff = Staff.create! valid_attributes
      delete :destroy, :id => staff.id
      response.should redirect_to(staffs_url)
    end
  end

end
