require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkplacesController do

  # This should return the minimal set of attributes required to create a valid
  # Workplace. As you add validations to Workplace, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all workplaces as @workplaces" do
      workplace = Workplace.create! valid_attributes
      get :index
      assigns(:workplaces).should eq([workplace])
    end
  end

  describe "GET show" do
    it "assigns the requested workplace as @workplace" do
      workplace = Workplace.create! valid_attributes
      get :show, :id => workplace.id
      assigns(:workplace).should eq(workplace)
    end
  end

  describe "GET new" do
    it "assigns a new workplace as @workplace" do
      get :new
      assigns(:workplace).should be_a_new(Workplace)
    end
  end

  describe "GET edit" do
    it "assigns the requested workplace as @workplace" do
      workplace = Workplace.create! valid_attributes
      get :edit, :id => workplace.id
      assigns(:workplace).should eq(workplace)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Workplace" do
        expect {
          post :create, :workplace => valid_attributes
        }.to change(Workplace, :count).by(1)
      end

      it "assigns a newly created workplace as @workplace" do
        post :create, :workplace => valid_attributes
        assigns(:workplace).should be_a(Workplace)
        assigns(:workplace).should be_persisted
      end

      it "redirects to the created workplace" do
        post :create, :workplace => valid_attributes
        response.should redirect_to(Workplace.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workplace as @workplace" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workplace.any_instance.stub(:save).and_return(false)
        post :create, :workplace => {}
        assigns(:workplace).should be_a_new(Workplace)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workplace.any_instance.stub(:save).and_return(false)
        post :create, :workplace => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workplace" do
        workplace = Workplace.create! valid_attributes
        # Assuming there are no other workplaces in the database, this
        # specifies that the Workplace created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Workplace.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => workplace.id, :workplace => {'these' => 'params'}
      end

      it "assigns the requested workplace as @workplace" do
        workplace = Workplace.create! valid_attributes
        put :update, :id => workplace.id, :workplace => valid_attributes
        assigns(:workplace).should eq(workplace)
      end

      it "redirects to the workplace" do
        workplace = Workplace.create! valid_attributes
        put :update, :id => workplace.id, :workplace => valid_attributes
        response.should redirect_to(workplace)
      end
    end

    describe "with invalid params" do
      it "assigns the workplace as @workplace" do
        workplace = Workplace.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workplace.any_instance.stub(:save).and_return(false)
        put :update, :id => workplace.id, :workplace => {}
        assigns(:workplace).should eq(workplace)
      end

      it "re-renders the 'edit' template" do
        workplace = Workplace.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workplace.any_instance.stub(:save).and_return(false)
        put :update, :id => workplace.id, :workplace => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workplace" do
      workplace = Workplace.create! valid_attributes
      expect {
        delete :destroy, :id => workplace.id
      }.to change(Workplace, :count).by(-1)
    end

    it "redirects to the workplaces list" do
      workplace = Workplace.create! valid_attributes
      delete :destroy, :id => workplace.id
      response.should redirect_to(workplaces_url)
    end
  end

end
